"""empty message

Revision ID: 20455ed82c14
Revises: f5497fffa722
Create Date: 2020-12-02 12:28:31.408847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20455ed82c14'
down_revision = 'f5497fffa722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['point_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    # ### end Alembic commands ###
