"""empty message

Revision ID: 342dd26b7e11
Revises: 4f42475b7be2
Create Date: 2020-12-03 14:51:50.334787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342dd26b7e11'
down_revision = '4f42475b7be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traindata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.Column('X', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('y', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['point_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traindata')
    # ### end Alembic commands ###
