"""empty message

Revision ID: 3c667a0d9532
Revises: bfd33d5f77e3
Create Date: 2020-12-03 23:01:45.746785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c667a0d9532'
down_revision = 'bfd33d5f77e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traindata', sa.Column('u_id', sa.Integer(), nullable=True))
    op.drop_constraint('traindata_g_id_fkey', 'traindata', type_='foreignkey')
    op.create_foreign_key(None, 'traindata', 'users', ['u_id'], ['id'])
    op.drop_column('traindata', 'g_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traindata', sa.Column('g_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'traindata', type_='foreignkey')
    op.create_foreign_key('traindata_g_id_fkey', 'traindata', 'users', ['g_id'], ['id'])
    op.drop_column('traindata', 'u_id')
    # ### end Alembic commands ###
