"""empty message

Revision ID: 4f42475b7be2
Revises: 20455ed82c14
Create Date: 2020-12-03 14:46:38.474897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f42475b7be2'
down_revision = '20455ed82c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traindata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.Column('X', sa.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['point_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traindata')
    # ### end Alembic commands ###
